<?php
global $connect;

$section = $connect->getFrom('sections', [], [
    'where' => ['id', $GLOBALS['url']['id']]
]);

?>
<section>
    <header>
        <h1><?= $section['title'] ?></h1>
    </header>
    <article>
        <form action="" method="POST" class="toolbar">
            <a href="/edit/<?= $section['id'] ?>" class="button">Редактировать</a>
            <a href="/" class="button">Назад</a>
        </form>
        <p><?= $section['description'] ?></p>
    </article>
</section>