<section>
    <form method="POST" action="">
        <label class="field">
            <div>Имя пользователя</div>
            <input type="text" name="username" required>
        </label>
        <label class="field">
            <div>Придумайте пароль</div>
            <input type="password" name="password" required>
        </label>
        <label class="field">
            <div>Повторите пароль</div>
            <input type="password" name="password" required>
        </label>
        <div class="field-set">
            <input type="submit" name="completeReg" value="Завершить">
            <a href="/">Вернуться назад</a>
        </div>
    </form>
</section>