<section>
    <header>
        <h1>Список разделов</h1>
    </header>
    <article>
        <form data-action="ExitFromAccount" class="toolbar">
            <a href="/add" class="button">Добавить раздел</a>
            <input type="submit" name="exit" value="Выйти">
        </form>
        <?php if (!empty($this->sections)) { ?>
            <div class="sections">
                <?php foreach ($this->sections as $section) { ?>
                    <section>
                        <div class="title"><?= $section['title'] ?></div>
                        <div class="tools">
                            <a href="/section/<?= $section['id'] ?>">Перейти</a>
                            <a href="/edit/<?= $section['id'] ?>">Редактировать</a>
                        </div>
                    </section>
                <?php } ?>
            </div>
        <?php } else { ?>
            <div class="message">Пока что нет ни одного раздела</div>
        <?php } ?>
    </article>
</section>