<section>
    <header>
        <h1>Список разделов</h1>
    </header>
    <article>
        <form action="" method="POST" class="toolbar">
            <a href="/add" class="button">Добавить раздел</a>
            <input type="submit" name="exit" value="Выйти">
        </form>
        <div class="sections">
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
            <section>
                <div class="title">Section One</div>
                <div class="tools">
                    <a href="/">Перейти</a>
                    <a href="/">Редактировать</a>
                </div>
            </section>
        </div>
    </article>
</section>