<section>
    <header>
        <h1>Добавить раздел</h1>
    </header>
    <article>
        <form action="" method="POST">
            <label class="field">
                <div>Заголовок</div>
                <input type="text" name="title" maxlength="100" autocomplete="off" required>
            </label>
            <label class="field">
                <div>Описание</div>
                <textarea name="description" rows="8"></textarea>
            </label>
            <div class="toolbar">
                <input type="submit" name="add" value="Добавить">
                <a href="/" class="button">Отмена</a>
            </div>
        </form>
    </article>
</section>