<section>
    <form method="POST" action="">
        <label class="field">
            <div>Имя пользователя</div>
            <input type="text" name="username">
        </label>
        <label class="field">
            <div>Пароль</div>
            <input type="password" name="password">
        </label>
        <div class="field-set">
            <input type="submit" value="Войти">
            <a href="/register">Зарегистрироваться</a>
        </div>
    </form>
</section>