<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,shrink-to-fit=no,viewport-fit=cover">
        <title><?= $page->title ?></title>
        <meta name="title" content="<?= $page->title ?>">
        <meta name="description" content="<?= $page->description ?>">
        <meta name="author" content="<?= $page->author ?>">
        <meta name="keywords" content="<?= $page->keywords ?>">
        <link rel="stylesheet" href="/themes/<?= $themeName ?>/styles/style.css" media="all">
    </head>
    <body>
        <main id="<?= $viewName ?>">
            <?= $page->content ?>
        </main>
    </body>
</html>
